name: CI

# Trigger the workflow on push or pull request
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Download Dependencies
        run: ./gradlew dependencies

      #- name: Check Kotlin Formatting
      #  run: ./gradlew ktlintCheck --continue

      - name: Run Tests
        run: ./gradlew test

      - name: Build & Test Project
        run: ./gradlew assemble --continue
