name: Dokka Publication

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Build pages with Gradle
        run: ./gradlew dokkaHtml
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build/dokka/html